### ISSUE TITLE
Smarter example coalescing/normalizing

### ISSUE THREAD

**Issue by olsona** [olsona/har_to_oas#2]
I've noticed that sometimes the exact same example will be written out twice. Here's an example from a HAR generated by navigating Reddit:
```
example-0001:
  value:
    listingOrder: []
    moderatedAfter: null
    moderatingProfiles: {}
    moderatingSubreddits: {}
    profiles: {}
    subredditAboutInfo: {}
    subreddits: {}
example-0002:
  value:
    listingOrder: []
    moderatedAfter: null
    moderatingProfiles: {}
    moderatingSubreddits: {}
    profiles: {}
    subredditAboutInfo: {}
    subreddits: {}
```

It would be cool if this tool could notice when two examples are the same and not print out the second one. I do see the relevant code, so I'm not sure how these examples are getting through.

Extra idea: user setting to let the tool check all relevant examples to see if they have the same typing, and if they do, only print out the first once. Maybe not all users want this, but it might be worthwhile, and could be a mildly interesting challenge.
